BUNDLE_NAME = RuePrefs

RuePrefs_FILES = RueRootVC.m
RuePrefs_CFLAGS = -fobjc-arc
RuePrefs_LIBRARIES = gcuniversal
RuePrefs_FRAMEWORKS = UIKit
RuePrefs_PRIVATE_FRAMEWORKS = Preferences
RuePrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
